@echo off

echo "Uninstall windows softwall"
winget.exe uninstall --name "Xbox Game Speech Window"
winget.exe uninstall --name "Xbox Game Bar Plugin"
winget.exe uninstall --name "Xbox TCUI"
winget.exe uninstall --name "Xbox Console Companion"
winget.exe uninstall --name "Xbox Game Bar"
winget.exe uninstall --name "Xbox Identity Provider"
winget.exe uninstall --name "Paint 3D"
winget.exe uninstall --name "3D Viewer"
winget.exe uninstall --name "MSN Weather"
winget.exe uninstall --name "Skype"
winget.exe uninstall --name "Cortana"
winget.exe uninstall --name "Microsoft People"
